### ISSUE TITLE
v0.0.4 didn't include the fix for #2

### ISSUE THREAD

**Issue by sargunv** [pragmaticivan/mikro-orm-entity-factory#6]
Thanks so much for the quick turnaround on releasing the fix in #3!

Unfortunately, looking at what's actually in the package, it didn't actually get the changes from the PR. Could you try building and releasing again?

Verified by downloading the package manually and inspecting the contents:

![image](https://user-images.githubusercontent.com/1320357/109724923-32418480-7b65-11eb-9e0e-62fb9a94ac8e.png)

**Comment by pragmaticivan** [comment]
Sorry about that. I unpublished v0.0.4 and waiting for npm to clear that out.

**Comment by pragmaticivan** [comment]
Will publish that as 0.1.0 now. Hopefully, I have some free time and will automate the release with https://github.com/pragmaticivan/mikro-orm-entity-factory/issues/4

**Comment by pragmaticivan** [comment]
mikro-orm-entity-factory@0.1.0 available.

**Comment by sargunv** [comment]
Thanks! Just getting into using it and realized that's not the only fix needed to make this not break when constructors exist (just as MikroORM lets you use any constructor you want). Will spend some more time on my local patch until I get it fully working and PR another fix later.
